### ISSUE TITLE
Feature request: (real-time) animated stft plot

### ISSUE THREAD

**Issue by mlaugharn** [SarthakYadav/audax#1]
Hi, one super useful utility would be a real-time animated stft plot. Would love to have this be part of the library, as I basically tried to implement this for another project and ended up not being able to crack the requisite matplotlib wrangling myself!

**Comment by SarthakYadav** [comment]
Hi @mlaugharn. 

Unfortunately, that's beyond the scope of this work. But thanks for your interest!

Closing this issue.
